### ISSUE TITLE
App crashing in some videos when going to PIP mode from portrait view.  Getting this error. (Check 7, 8 & 9th log line)

### ISSUE THREAD

**Issue by SweetD3v** [lzls/Videos#9]
java.lang.IllegalArgumentException: enterPictureInPictureMode: Aspect ratio is too extreme (must be between 0.418410 and 2.390000).
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.os.Parcel.readException(Parcel.java:2294)
        at android.app.IActivityTaskManager$Stub$Proxy.enterPictureInPictureMode(IActivityTaskManager.java:7048)
        at android.app.Activity.enterPictureInPictureMode(Activity.java:2900)
        at com.liuzhenlin.videos.view.activity.VideoActivity$3.onViewModeChange(VideoActivity.java:416)
        at com.liuzhenlin.texturevideoview.TextureVideoView.setViewMode(TextureVideoView.java:1690)
        at com.liuzhenlin.texturevideoview.TextureVideoView$OnChildClickListener.onClick(TextureVideoView.java:3167)
        at android.view.View.performClick(View.java:8160)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30250)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityTaskManagerService.ensureValidPictureInPictureActivityParamsLocked(ActivityTaskManagerService.java:5165)
        at com.android.server.wm.ActivityTaskManagerService.enterPictureInPictureMode(ActivityTaskManagerService.java:5031)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:3348)
        at android.os.Binder.execTransactInternal(Binder.java:1195)
        at android.os.Binder.execTransact(Binder.java:1159)

**Comment by lzls** [comment]
OK. Thank you for your bug reporting first.
This is crashed due to we want to switch the window to PiP mode with the same aspect ratio as the played video, which has been considered too extreme by the system framework, i.e., it is out of the supported ratio range from 0.418410 to 2.390000).
In fact, I have already known about this issue, but I just leaved it aside as the videos with extreme aspect ratio are not so common. This should be fixed by simply clamping the aspect ratio to fit within the supported range before switching the window to PiP, leaving black bars around the video content.

**Comment by lzls** [comment]
OK. Thank you for your bug reporting first.

This is crashed due to we want to switch the window to PiP mode with the same aspect ratio as the played video, which has been considered too extreme by the system framework, i.e., it is out of the supported ratio range from 0.418410 to 2.390000).

In fact, I have already known about this issue, but I just leaved it aside as the videos with extreme aspect ratio are not so common. This should be fixed by simply clamping the aspect ratio to fit within the supported range before switching the window to PiP, leaving black bars around the video content.
